"""criar tabelas usuarios pedidos itens

Revision ID: a3abff7da3b7
Revises: 75602dec1984
Create Date: 2026-05-21 15:01:16.207795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3abff7da3b7'
down_revision: Union[str, Sequence[str], None] = '75602dec1984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
